### PR TITLE
covr: already setup by Robin

### PR DESCRIPTION
**Pull request by layik**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Awesome, will check 2mo.

**Review by Robinlovelace — APPROVED** [review]
Looks good, although not sure tests are important in this early + experimental stage of the codebase lifecycle. Focus for me is on mvp, but tests can definitely help with that and it's good to know how much (or little) of the codebase we're covering with unit tests. Many thanks Layik!

**Comment by layik** [comment]
@Robinlovelace focus for me must be on tests even before any code is written. Feel free to write code as you do and I will `covr` it. The examples are great and will reuse them, but unit tests are just the least I must be doing if not full TDD.

**Comment by Robinlovelace** [comment]
test driven development, sounds good :+1:

**Comment by Robinlovelace** [comment]
just looked it up: https://en.wikipedia.org/wiki/Test-driven_development

**Pull request merged**
