### PR TITLE
Import upset pkg, require R 3.5.0, update example

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @layik  I think this is good to go. Tests fail on Windows because of a quirk: jsonlite is being updated so Windows binary is not yet built I think, causing the fail: https://github.com/saferactive/trafficalmr/runs/1092258231#step:12:237

**Comment by layik** [comment]
Will definitely have a look later tonight.

**Review by layik — APPROVED** [review]

**Comment by Robinlovelace** [comment]
Thanks for `document()`ing the changes!

**Comment by Robinlovelace** [comment]
Merging as the first tests are passing :+1:

**Pull request merged**
